version: '3'

services:
  db:
    image:
      romeo7/reunion-db:latest
    
    volumes:
      - ./backup.sql:/var/local/backup.sql
      - ./initdb-custom.sh:/docker-entrypoint-initdb.d/initdb-custom.sh
    ports:
      - "5432:5432"
    

  web:
    image:
      romeo7/reunion-web:latest
    command: >
      sh -c "sleep 30 &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./web:/app
    ports:
      - "8001:8000"
    depends_on:
      - db 
