# Use an official PostgreSQL image as the base image
FROM postgres:15.4

# Set environment variables
ENV POSTGRES_DB=reapion
ENV POSTGRES_USER=romeo7
ENV POSTGRES_PASSWORD=goldroger3

# Expose the PostgreSQL port
EXPOSE 5432